Remove .git dir from package + other fixes
- Remove .git dir from package
- Fix post_install/upgrade function error return value
- Remove entire /opt/stable-diffusion-webui directory when uninstalling

diff --git a/stable-diffusion-webui-git.install b/stable-diffusion-webui-git.install
--- a/stable-diffusion-webui-git.install
+++ b/stable-diffusion-webui-git.install
@@ -52,18 +52,17 @@ _install() {
         wget --progress=bar:force:noscroll \
               -O "${model_dir}/${model_file}" "${_model_url}" || return 1
     fi
-
 }
 
 post_install() {
-    _install || echo -e "\nERROR: Failed to install dependencies\n"
+    _install || { echo -e "\nERROR: Failed to install dependencies\n"; return 1; }
 }
 
 post_upgrade() {
-    _install || echo -e "\nERROR: Failed to install dependencies\n"
+    _install || { echo -e "\nERROR: Failed to install dependencies\n"; return 1; }
 }
 
 post_remove() {
-    echo "Cleaning up virtual environment for $_appname..."
-    rm -rf "${_apphome}/venv"
+    echo "Removing ${_apphome}..."
+    rm -rf "${_apphome}"
 }
